### ISSUE TITLE
Filters Do Not Persist

### ISSUE THREAD

**Issue by jho-md** [umbraco/Umbraco.UIBuilder.Issues#156]
**Describe the bug**
When selecting an option for a filter, the filter works as expected. However, when you navigate back to the filter, the filter appears unset rather than showing the previously selected option.

**Steps To Reproduce**
1. Configure a collection with a dropdown filter.
2. Create some sample entities.
3. Choose one of the dropdown choices for the filter and see that the filter works as expected.
4. Navigate back to the filter and see that the filter appears unset rather than persisting the previous selection.

**Expected behavior**
Navigating back to the filter should persist the previous selection. 

**Environment (please complete the following information):**
 - Server OS: Windows
 - Browser: Chrome
 - Umbraco Version: 15.3.0
 - Product Version: 15.1.2

---
_This item has been added to our backlog AB#51958_

**Comment by nathanwoulfe** [comment]
@jho-md and again with the pending PR. Will aim to wrap up a few more issues and get a patch out soon.

**Comment by acoumb** [comment]
Hi @jho-md ,

This has been fixed with version [`15.1.3`](https://www.nuget.org/packages/Umbraco.UIBuilder/15.1.3) of UI Builder.

Thanks,
Adrian

**Comment by jho-md** [comment]
@acoumb @nathanwoulfe Just upgraded to the latest and still having this issue. After setting the filter and applying, I click on the filter again and it appears unset.

**Comment by andrejd22** [comment]
@acoumb same, issue still exists. This issue is partially resolved. Now, after clicking on a collection item, opening the modal, and then closing it, the filters remain as expected. However, if the user navigates to a different collection and then returns, the filters are lost. This might be acceptable behavior, but in previous versions (13.x.x), filters were saved in Local Storage. We had a custom field implementation with a button that, when clicked, would apply the filters and open the collection with the filtered items. However, this is no longer possible in the current version. Since Local Storage based persistence no longer works, maybe query string parameters could be used to apply and persist filters across navigation?

**Comment by acoumb** [comment]
Hi @andrejd22 ,

I've added the local storage persistence for filters with version [`15.1.7`](https://www.nuget.org/packages/Umbraco.UIBuilder/15.1.7).

Thanks,
Adrian

**Comment by jho-md** [comment]
Hi @acoumb ,

I am still experiencing the original issue. When I set a filter and navigate back to it, the UI does not show the previously selected filter, it just shows blank dropdowns. Additionally, if I hit submit on that filter with nothing set, it throws an API error. Please see the below video for an example of this behavior.

https://drive.google.com/file/d/1gEhWlo1GqX1fkKr-j8IiKYQ3znQ-yEgD/view?usp=sharing

Can you replicate this error, or do we have something configured incorrectly?

**Comment by adavidovic92** [comment]
@acoumb It works fine for me. All filters which were added in local storage are always set. Thank you.

P.S. it was nice to see and hear you on Codegarden 2025

**Comment by acoumb** [comment]
> Hi [@acoumb](https://github.com/acoumb) ,
> 
> I am still experiencing the original issue. When I set a filter and navigate back to it, the UI does not show the previously selected filter, it just shows blank dropdowns. Additionally, if I hit submit on that filter with nothing set, it throws an API error. Please see the below video for an example of this behavior.
> 
> https://drive.google.com/file/d/1gEhWlo1GqX1fkKr-j8IiKYQ3znQ-yEgD/view?usp=sharing
> 
> Can you replicate this error, or do we have something configured incorrectly?

Hi @jho-md ,

This has been fixed with patch version `15.1.8`.

Adrian
