### ISSUE TITLE
Custom validation exceptions not displayed in UI during save

### ISSUE THREAD

**Issue by andrejd22** [umbraco/Umbraco.UIBuilder.Issues#182]
**Describe the bug**
When using a custom repository that includes validation logic during save, exceptions are correctly thrown when validation fails. However, the UI only displays a generic error message stating that validation failed. The actual custom validation message is present in the response's `detail` property, but it's not surfaced to the user.

**Steps To Reproduce**
1. Implement a custom repository with validation logic that throws an exception (e.g., `throw new Exception("Custom validation message")`) during save
2. In the backoffice, go to the entity that uses this custom logic
3. Click `Save` on the form while triggering a validation failure
4. Observe that a generic error message is shown in the UI, even though a more detailed message is present in the response.

**Expected behavior**
The UI should display the custom validation message returned in the detail property of the error response, providing users with specific feedback instead of a generic failure message. This improves clarity and helps users correct their input without needing to inspect the network response manually.

**Screenshots**

<img width="1852" height="1033" alt="Image" src="https://github.com/user-attachments/assets/3ac12db1-7955-45e2-99ef-9a1bc7918b05" />

**Environment (please complete the following information):**
 - Server OS: Windows
 - Browser: Chrome
 - Umbraco Version: 16.0.0
 - Product Version: 16.0.2

---
_This item has been added to our backlog AB#54921_

**Comment by acoumb** [comment]
Hi @andrejd22 ,

This has been addressed in version `16.0.3` of UI Builder.

Thanks, 
Adrian

**Comment by andrejd22** [comment]
@acoumb unfortunately, the issue still persists, and I continue to see the same message

**Comment by andrejd22** [comment]
@acoumb thank you, the issue is solved.

**Comment by andrejd22** [comment]
@acoumb sorry, it seems this issue is still here. The message was different this time — it said our license has expired, even though I thought it was working 😄

**Comment by acoumb** [comment]
@andrejd22 if it's a license related issue, could you move it separately? I already have something on the backlog. Thanks
