### ISSUE TITLE
In object extensions the name property does not seem to handle expressions pointing to nested objects in 13

### ISSUE THREAD

**Issue by dennispedersenakqa** [umbraco/Umbraco.UIBuilder.Issues#97]
**Describe the bug**
Every uniquerow in my ui builder list has a row connected to it by relational database, however when it comes to the view the "Row" attribute does not print anything.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/127423343/b1d76530-ec87-48df-8f2d-bd802b110904)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/127423343/0a3a3287-9f84-4a2f-bff7-158076dff5da)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/127423343/28fb09d7-271c-4358-a9b3-33fcd44d478d)
(The "D" you see in name right now is "Lang" from the unique row.
**Steps To Reproduce**
1. Create 2 tables, where one refers to the other one (one can have many of the other)
2. Just try to load the backoffice ui builder list view and get presented with data only from the unique table

**Expected behavior**
The list view would show 6 different fields. however it only shows the Name property

**Environment (please complete the following information):**
 - Server OS: Local windows machine
 - Browser Chrome
 - Umbraco Version 13.2.2
 - Product Version 13.1.1

**Additional context**
In umbraco 12 this worked as expected. And when I look at my custom repository I can see that I return a full unique row back with all properties. However it's not showing

**Comment by krebil** [comment]
This seems to be a problem with the property expression handling rather than the underlying relation. 

In object extensions the name property does not seem to handle expressions pointing to nested objects. This worked in v12.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1363512/aa86e359-8438-4282-8429-6cadebd97ff1)

**Comment by acoumb** [comment]
Hi @dennispedersenakqa ,

The issue has been fixed with the [13.1.2](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.2) minor release.

Thank you,
Adrian

**Comment by krebil** [comment]
@acoumb 

This is still an issue for searchable properties. It throws an exception in EntityService.FindEntities when the expression points to nested objects.

`System.ArgumentException: Property 'System.String Number' is not defined for type 'Models.DTOs.PatternDTO' (Parameter 'property')`

Itt looking for the number property on a model that doesn't have it. The expression looks like: 
`.AddSearchableProperty(x => x.Row.Number)`

**Comment by acoumb** [comment]
Hi @krebil ,

Thank you for bringing this to our attention. Currently `UIBuilder` does not support using nested objects as searchable in any version, but I will be looking into options for adding support to this use case.

Adrian

**Comment by acoumb** [comment]
Hi @krebil ,

I've added support for properties of nested objects with the latest [13.1.4](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.4) release.

Thanks,
Adrian
